INSERT INTO Todos VALUES (DEFAULT, 'Clark Kent', 'OUT', '2018-11-22', 'Brand new', 'Grapes of Wrath');
INSERT INTO Todos VALUES (DEFAULT,'John Doe', 'IN-TRANSIT', '2018-10-11', 'Used', 'Extreme Ownership');
INSERT INTO Todos VALUES (DEFAULT,'Wonder Woman', 'IN', '2018-06-15', 'Used', 'Leonardo da Vinci');
INSERT INTO Todos VALUES (DEFAULT, 'Bruce Lee', 'IN', '2018-03-24', 'New', 'Great Expectations');
INSERT INTO Todos VALUES (DEFAULT,'Captain America', 'OUT', '2018-12-09', 'Used', 'DevOps Handbook');
INSERT INTO Todos VALUES (DEFAULT, 'Bruce Lee', 'IN', '2018-03-24', 'New', 'Great Expectations V1');
INSERT INTO Todos VALUES (DEFAULT, 'Bruce Lee', 'IN', '2018-03-24', 'New', 'Master in Java');
INSERT INTO Todos VALUES (DEFAULT, 'Bruce Lee', 'IN', '2018-03-24', 'New', 'Rest API');
INSERT INTO Todos VALUES (DEFAULT, 'Bruce Lee', 'IN', '2018-03-24', 'New', 'Spring');
INSERT INTO Todos VALUES (DEFAULT, 'Bruce Lee', 'IN', '2018-03-24', 'New', 'GitHub);